site_info:
  title: "malaika handa"
  author: "Malaika Handa"
  description: "My name is Malaika Handa and I make lots of crossword puzzles."
  share_image: "og-image.png"
  url: "https://parker-thinkpad-p15s.banjo-galaxy.ts.net/"
  twitter: "@malisolves"

theme_colors:
    background: "#b3b3b3"
    color-1: "#e8e8e8"
    color-2: "#dd95ed"
    color-3: "#b01c72"
    color-4: "#460050"

bio:
  intro: >-
    My name is Malaika Handa and I've made {crossword_count} crossword puzzles.
  details: >-
    You'll find me in [Vulture magazine](https://www.vulture.com/2022/01/introducing-the-vulture-10x10-daily-crossword-puzzle.html)
    several days a week, and writing for [rexwordpuzzle](https://rexwordpuzzle.blogspot.com/p/frequently-asked-questions-i-get-lots.html)
    about once a month. I'm also sporadically published in other outlets (see below);
    if you'd like to get an email when that happens, [sign up here](https://groups.google.com/g/girlbosswords).
    In the past, I ran [the 7xwords project](https://www.7xwords.com/) and blogged for 
    [Diary of a Crossword Fiend](https://crosswordfiend.com/).
  connect: >-
    When I'm not crossword-ing, I write code, play volleyball, teach high schoolers computer science,
    drink cocktails, and [read romance novels](https://tinyurl.com/malaikas-romance-recs).
    Find me on [Twitter](https://x.com/malisolves), [bluesky](https://bsky.app/profile/malaika-h.bsky.social)
    or [Instagram](https://www.instagram.com/malihanda/). Or, email works too: handa malaika at gmail dot com.

footer:
  text: >-
    This website was built by [Parker](https://parkerhiggins.net).